### ISSUE TITLE
[Heart Attack] Clarissa uses JP dub randomly

### ISSUE THREAD

**Issue by Blackbird88** [ksdomino/OR2LouderEngineSound#1]
> I know it doesn't work on heart attack mode (because there were just too many sounds to edit (would take too long using the currently available tools and limited automation available).

Despite the description stating it doesn't touch Heart Attack, it causes Clarissa to use JP dub for some reason

**Comment by ksdomino** [comment]
All I did was lower the volume of the all the pak files except for the engine ones. I didn't touch the ones with HAM in their name so this issue is most likely unrelated but I do remember that there are some files with JP and HAM in their name so maybe some files renamed by accident. Let me know how to reproduce the error on mine and I'm happy do some testing.

**Comment by Tenome** [comment]
On a similar note, the announcer only says the car/mode names in English, and is mute if you have it set to other languages. I wonder if that can be fixed. Are there English dub files in the other language paks?

**Comment by ksdomino** [comment]
It's possible to check the .pak files using the free app: audacity. (Select File > Import > Raw Data ).
Personally I only wanted to fix overloud road noises & bad balance.

To extract the .pak files, use : https://www.watto.org/game_extractor.html
The free version allows extracting the files but not replacing them. I dropped $10 for the paid version to be able to replace the files. Make sure to email them first to make sure they send the version for Outrun 2 pak files - I'm not sure whether they merged it into main yet.

**Comment by Blackbird88** [comment]
> Let me know how to reproduce the error on mine and I'm happy do some testing.

I installed the mod and started Heart Attack, doesn't matter if OR2 or SP, Clarissa's voice lines use JP dub.

**Comment by Tenome** [comment]
Ah, so this was already an issue here. I have the same issue, it also sounds like it's pitch-shifted.

https://streamable.com/59ljf6

**Comment by ksdomino** [comment]
Fixed in the latest release (please see release notes for the reason). Overwrite the previous files with the ones in the latest release to fix the issue.

**Comment by Blackbird88** [comment]
Bug is gone with last release. I assumed it was erroneously shipped file, it happens.
